global:
  scrape_interval: 45s
  scrape_timeout: 30s

scrape_configs:
  - job_name: 'Whmcs-Tickets'
    static_configs:
      - targets: ['whmcs-ticketexporter:80']

    scrape_timeout: 30s
    scrape_interval: 5m
